/**
 * Calendar Export Utilities (.ics / iCalendar RFC 5545)
 * 
 * Extracts and exports legal deadlines and key dates to calendar format.
 */

/**
 * Escape text for iCalendar format.
 * @param {string} str
 * @returns {string}
 */
export function escapeIcsText(str) {
  if (!str) return '';
  return String(str)
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\r?\n/g, '\\n');
}

/**
 * Format Date object to ICS UTC string: YYYYMMDDTHHmmssZ
 * @param {Date} date
 * @returns {string}
 */
export function formatDateToIcs(date) {
  const d = date instanceof Date && !isNaN(date) ? date : new Date();
  const pad = (n) => String(n).padStart(2, '0');
  
  const year = d.getUTCFullYear();
  const month = pad(d.getUTCMonth() + 1);
  const day = pad(d.getUTCDate());
  const hours = pad(d.getUTCHours());
  const minutes = pad(d.getUTCMinutes());
  const seconds = pad(d.getUTCSeconds());

  return `${year}${month}${day}T${hours}${minutes}${seconds}Z`;
}

/**
 * Format Date to All-Day ICS string: YYYYMMDD
 * @param {Date} date
 * @returns {string}
 */
export function formatDateToIcsDay(date) {
  const d = date instanceof Date && !isNaN(date) ? date : new Date();
  const pad = (n) => String(n).padStart(2, '0');
  return `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}`;
}

/**
 * Attempt to parse a natural or formatted date string into a Date object.
 * @param {string} dateStr
 * @returns {Date}
 */
export function parseDateString(dateStr) {
  if (!dateStr || typeof dateStr !== 'string') {
    const fallback = new Date();
    fallback.setDate(fallback.getDate() + 14); // 2 weeks default
    return fallback;
  }

  // 1. Direct standard parse
  const direct = new Date(dateStr);
  if (!isNaN(direct.getTime())) {
    return direct;
  }

  // 2. Relative regex matches (e.g. "within 30 days", "30 days from execution", "14 business days")
  const daysMatch = dateStr.match(/(\d+)\s*(?:business\s*)?days?/i);
  if (daysMatch) {
    const days = parseInt(daysMatch[1], 10);
    const future = new Date();
    future.setDate(future.getDate() + days);
    return future;
  }

  const monthsMatch = dateStr.match(/(\d+)\s*months?/i);
  if (monthsMatch) {
    const months = parseInt(monthsMatch[1], 10);
    const future = new Date();
    future.setMonth(future.getMonth() + months);
    return future;
  }

  const yearsMatch = dateStr.match(/(\d+)\s*years?/i);
  if (yearsMatch) {
    const years = parseInt(yearsMatch[1], 10);
    const future = new Date();
    future.setFullYear(future.getFullYear() + years);
    return future;
  }

  // Fallback: 14 days out
  const fallback = new Date();
  fallback.setDate(fallback.getDate() + 14);
  return fallback;
}

/**
 * Generate iCalendar (.ics) format string for an array of legal events.
 * @param {Array<{ date: string, event: string, action?: string, details?: string }>} events
 * @param {string} [docTitle]
 * @returns {string}
 */
export function generateIcsContent(events = [], docTitle = 'Legal Document') {
  const now = new Date();
  const nowIcs = formatDateToIcs(now);
  const title = docTitle || 'Legal Document';

  const vEvents = events.map((item, index) => {
    const targetDate = parseDateString(item.date);
    const nextDay = new Date(targetDate);
    nextDay.setDate(nextDay.getDate() + 1);

    const uid = `legallens-${Date.now()}-${index}@legallens.ai`;
    const summary = escapeIcsText(`[LegalLens] ${item.event || 'Legal Deadline'}`);
    const description = escapeIcsText(
      `Document: ${title}\n` +
      `Date / Timeline: ${item.date || 'N/A'}\n` +
      (item.action ? `Required Action: ${item.action}\n` : '') +
      (item.details ? `Details: ${item.details}\n` : '') +
      `\n⚠️ Generated by LegalLens AI — Verify against your signed contract.`
    );

    const dtStart = formatDateToIcsDay(targetDate);
    const dtEnd = formatDateToIcsDay(nextDay);

    return [
      'BEGIN:VEVENT',
      `UID:${uid}`,
      `DTSTAMP:${nowIcs}`,
      `DTSTART;VALUE=DATE:${dtStart}`,
      `DTEND;VALUE=DATE:${dtEnd}`,
      `SUMMARY:${summary}`,
      `DESCRIPTION:${description}`,
      'STATUS:CONFIRMED',
      'TRANSP:TRANSPARENT',
      'BEGIN:VALARM',
      'ACTION:DISPLAY',
      `DESCRIPTION:${summary}`,
      'TRIGGER:-P1D',
      'END:VALARM',
      'END:VEVENT',
    ].join('\r\n');
  }).join('\r\n');

  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//LegalLens AI//Legal Document Calendar Export//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:Legal Deadlines - ${escapeIcsText(title)}`,
    vEvents,
    'END:VCALENDAR',
  ].filter(Boolean).join('\r\n');
}

/**
 * Download a string content as an .ics file in the browser.
 * @param {string} filename
 * @param {string} content
 */
export function downloadIcsFile(filename, content) {
  if (typeof window === 'undefined') return;
  
  const cleanFilename = (filename || 'legal-deadlines')
    .replace(/[^a-z0-9-_]/gi, '_')
    .toLowerCase() + '.ics';

  const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', cleanFilename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Helper to export a single date item.
 * @param {{ date: string, event: string, action?: string }} item
 * @param {string} [docTitle]
 */
export function exportSingleDateIcs(item, docTitle = 'Legal Document') {
  if (!item) return;
  const content = generateIcsContent([item], docTitle);
  const filename = `${docTitle || 'deadline'}-${item.event || 'date'}`.slice(0, 30);
  downloadIcsFile(filename, content);
}

/**
 * Helper to export all date items.
 * @param {Array<{ date: string, event: string, action?: string }>} items
 * @param {string} [docTitle]
 */
export function exportAllDatesIcs(items, docTitle = 'Legal Document') {
  if (!items || items.length === 0) return;
  const content = generateIcsContent(items, docTitle);
  const filename = `${docTitle || 'legal'}-all-deadlines`;
  downloadIcsFile(filename, content);
}
