/**
 * Report Export Utilities
 * 
 * Generates structured text/markdown reports and triggers print/PDF formatting.
 */

/**
 * Generate a Markdown report for any analysis type.
 * @param {string} analysisType - 'simplify' | 'risk' | 'checklist' | 'lawyer-prep' | 'compare' | 'negotiate'
 * @param {object} data - Analysis result data
 * @param {string} [docTitle] - Document title
 * @returns {string}
 */
export function generateMarkdownReport(analysisType, data, docTitle = 'Legal Document') {
  if (!data) return '';

  const timestamp = new Date().toLocaleString();
  const header = [
    `# ⚖️ LegalLens AI — Document Analysis Report`,
    `**Document:** ${data.title || docTitle}`,
    `**Analysis Type:** ${analysisType.toUpperCase()}`,
    `**Date Generated:** ${timestamp}`,
    `\n> ⚠️ **DISCLAIMER**: This report is generated by LegalLens AI for informational and educational purposes only. It does not constitute legal advice and does not create an attorney-client relationship. Always consult a licensed attorney for specific legal matters.`,
    `\n---\n`,
  ].join('\n');

  let body = '';

  if (analysisType === 'simplify') {
    body += `## 📋 Document Overview\n`;
    if (data.documentType) body += `- **Document Type:** ${data.documentType}\n`;
    if (data.readingLevel) body += `- **Original Reading Level:** ${data.readingLevel}\n`;
    if (data.tldr) body += `\n### ⚡ TL;DR\n${data.tldr}\n\n`;
    if (data.summary) body += `### 📝 Summary\n${data.summary}\n\n`;

    if (data.sections && data.sections.length > 0) {
      body += `## 📑 Section-by-Section Breakdown\n\n`;
      data.sections.forEach((sec, i) => {
        body += `### ${i + 1}. ${sec.simplifiedHeading || sec.originalHeading} [Importance: ${sec.importance || 'Medium'}]\n`;
        body += `**Plain-English Explanation:**\n${sec.simplifiedText}\n\n`;
        if (sec.originalText) {
          body += `> **Original Contract Excerpt:**\n> "${sec.originalText}"\n\n`;
        }
      });
    }

    if (data.keyTerms && data.keyTerms.length > 0) {
      body += `## 📚 Key Legal Terms Glossary\n\n`;
      data.keyTerms.forEach(term => {
        body += `- **${term.term}:** ${term.definition}\n`;
      });
      body += '\n';
    }
  } else if (analysisType === 'risk') {
    body += `## 🛡️ Risk Assessment Summary\n`;
    body += `- **Overall Risk Level:** ${data.overallRiskLevel?.toUpperCase() || 'UNKNOWN'}\n`;
    body += `- **Summary:** ${data.overallRiskSummary || 'N/A'}\n\n`;

    if (data.redFlags && data.redFlags.length > 0) {
      body += `## 🚩 Red Flags (High Priority)\n\n`;
      data.redFlags.forEach((flag, i) => {
        body += `### ⛔ ${i + 1}. ${flag.title}\n`;
        body += `- **Concern:** ${flag.description}\n`;
        if (flag.clause) body += `- **Clause Reference:** ${flag.clause}\n`;
        body += '\n';
      });
    }

    if (data.risks && data.risks.length > 0) {
      body += `## ⚠️ Identified Risks & Recommendations\n\n`;
      data.risks.forEach((risk, i) => {
        body += `### ${i + 1}. ${risk.title} [Severity: ${risk.severity}]\n`;
        body += `${risk.description}\n`;
        if (risk.recommendation) body += `💡 **Recommendation:** ${risk.recommendation}\n`;
        body += '\n';
      });
    }

    if (data.obligations && data.obligations.length > 0) {
      body += `## 📋 Obligations & Deadlines\n\n`;
      data.obligations.forEach((obl, i) => {
        body += `### ${obl.id || `Obligation ${i + 1}`} (Party: ${obl.party || 'You'})\n`;
        body += `- **Requirement:** ${obl.description}\n`;
        if (obl.deadline) body += `- **Deadline:** ${obl.deadline}\n`;
        if (obl.consequence) body += `- **Consequence if missed:** ${obl.consequence}\n`;
        body += '\n';
      });
    }

    if (data.missingClauses && data.missingClauses.length > 0) {
      body += `## ❓ Potentially Missing Standard Clauses\n\n`;
      data.missingClauses.forEach((m, i) => {
        body += `### ${i + 1}. ${m.clause}\n`;
        body += `- **Why Important:** ${m.importance}\n`;
        body += `- **Recommendation:** ${m.recommendation}\n\n`;
      });
    }
  } else if (analysisType === 'checklist') {
    body += `## ✅ Actionable Checklist\n\n`;
    if (data.beforeSigning && data.beforeSigning.length > 0) {
      body += `### 📋 Before Signing\n`;
      data.beforeSigning.forEach(item => {
        body += `- [ ] **[${item.priority?.toUpperCase()}]** ${item.task}${item.details ? ` — ${item.details}` : ''}\n`;
      });
      body += '\n';
    }

    if (data.afterSigning && data.afterSigning.length > 0) {
      body += `### 📌 After Signing\n`;
      data.afterSigning.forEach(item => {
        body += `- [ ] **[${item.priority?.toUpperCase()}]** ${item.task}${item.deadline ? ` (Deadline: ${item.deadline})` : ''}\n`;
      });
      body += '\n';
    }

    if (data.keyDates && data.keyDates.length > 0) {
      body += `### 📅 Key Dates\n`;
      data.keyDates.forEach(date => {
        body += `- **${date.date}:** ${date.event} (Action: ${date.action})\n`;
      });
      body += '\n';
    }
  } else if (analysisType === 'lawyer-prep') {
    body += `## 🧑‍⚖️ Pre-Consultation Lawyer Brief\n\n`;
    if (data.briefingSummary) body += `### 📝 Executive Summary for Attorney\n${data.briefingSummary}\n\n`;
    if (data.estimatedComplexity) body += `- **Estimated Complexity:** ${data.estimatedComplexity}\n`;
    if (data.suggestedLawyerType) body += `- **Recommended Specialist:** ${data.suggestedLawyerType}\n\n`;

    if (data.questionsToAsk && data.questionsToAsk.length > 0) {
      body += `### ❓ Questions to Ask Your Lawyer\n`;
      data.questionsToAsk.forEach((q, i) => {
        body += `${i + 1}. **${q.question}** [Priority: ${q.priority}]\n`;
        if (q.context) body += `   *Context:* ${q.context}\n`;
      });
      body += '\n';
    }

    if (data.documentsToGather && data.documentsToGather.length > 0) {
      body += `### 📂 Documents to Bring to Consultation\n`;
      data.documentsToGather.forEach(doc => {
        body += `- **${doc.document}:** ${doc.reason}\n`;
      });
      body += '\n';
    }
  } else if (analysisType === 'compare') {
    body += `## ⚖️ Document Comparison Summary\n\n`;
    if (data.summaryOfChanges) body += `${data.summaryOfChanges}\n\n`;
    if (data.overallAssessment) body += `**Overall Assessment:** ${data.overallAssessment}\n\n`;
    if (data.recommendation) body += `💡 **Recommendation:** ${data.recommendation}\n\n`;

    if (data.differences && data.differences.length > 0) {
      body += `## 🔍 Detailed Differences\n\n`;
      data.differences.forEach((diff, i) => {
        body += `### ${i + 1}. ${diff.category} in ${diff.section || 'Document'} [Impact: ${diff.significance}]\n`;
        body += `- **Doc A:** ${diff.documentAText || 'Not present'}\n`;
        body += `- **Doc B:** ${diff.documentBText || 'Not present'}\n`;
        body += `- **Explanation:** ${diff.explanation}\n`;
        if (diff.impact) body += `- **Impact:** ${diff.impact}\n`;
        body += '\n';
      });
    }
  }

  return header + body;
}

/**
 * Trigger download of Markdown/Text file.
 * @param {string} filename
 * @param {string} content
 */
export function downloadTextReport(filename, content) {
  if (typeof window === 'undefined') return;

  const cleanFilename = (filename || 'legallens-report')
    .replace(/[^a-z0-9-_]/gi, '_')
    .toLowerCase() + '.md';

  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', cleanFilename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Trigger browser print dialog for PDF export.
 */
export function triggerPrintReport() {
  if (typeof window !== 'undefined') {
    window.print();
  }
}
